;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	bison-electric-close-brace
	bison-electric-open-brace
	bison-electric-semicolon
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-paren
	c-electric-pound
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-indent-line-or-region
	dabbrev-expand
	down-list
	electric-pair-delete-pair
	forward-sexp
	kill-sexp
	markdown-outdent-or-delete
	))

(setq mc/cmds-to-run-once
      '(
	handle-switch-frame
	))
