;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	bison-electric-close-brace
	bison-electric-open-brace
	bison-electric-semicolon
	c-electric-brace
	c-electric-paren
	c-electric-pound
	c-electric-semi&comma
	electric-pair-delete-pair
	))

(setq mc/cmds-to-run-once
      '(
	handle-switch-frame
	))
